In [1]:
import numpy as np
import pandas as pd

marks=np.array([44,55,67,21,93])
print("Original Array:")
print(marks)

print("---NumPy Indexing---")
print("First mark:", marks[0])
print("Last mark:", marks[-1])
print("second element:", marks[1])

print("---NumPy Slicing---")
print("marks from start to third element:", marks[0:3])
print("print elements in reverse order:", marks[::-1])
print("print every second element:", marks[::2])
print("print elements from inde 2 to 4", marks[2:5])




Original Array:
[44 55 67 21 93]
---NumPy Indexing---
First mark: 44
Last mark: 93
second element: 55
---NumPy Slicing---
marks from start to third element: [44 55 67]
print elements in reverse order: [93 21 67 55 44]
print every second element: [44 67 93]
print elements from inde 2 to 4 [67 21 93]


In [4]:
#2 D Array
arr=np.array([
    [22, 45, 67, 52],
    [34, 87, 99, 21],
    [55, 71, 23, 51],
    [44, 19,28, 83]
])
print(arr)

[[22 45 67 52]
 [34 87 99 21]
 [55 71 23 51]
 [44 19 28 83]]
